"""empty message

Revision ID: bffffc1378d0
Revises: 34a0d8dfe5ed
Create Date: 2022-04-13 01:05:21.025556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffffc1378d0'
down_revision = '34a0d8dfe5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocerys', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocerys', 'date')
    # ### end Alembic commands ###
